#if WITH_DEV_AUTOMATION_TESTS

#include "Tests/UnrealAgentAcpProtocolTestHelpers.h"

namespace UnrealAgent::AutomationTests
{
    FString MakeFakeAcpScript()
    {
        return FString()
            + TEXT("#!/usr/bin/python3\n")
            + TEXT("import json, signal, sys\n")
            + TEXT("if hasattr(signal, 'SIGPWR') and signal.getsignal(signal.SIGPWR) == signal.SIG_IGN:\n")
            + TEXT("    print('fake ACP inherited ignored SIGPWR', file=sys.stderr, flush=True)\n")
            + TEXT("    sys.exit(42)\n")
            + TEXT("session_id = 'fake-session'\n")
            + TEXT("prompt_id = None\n")
            + TEXT("permission_id = 1000\n")
            + TEXT("current_model = 'model-a'\n")
            + TEXT("current_thinking = 'medium'\n")
            + TEXT("current_agent = 'build'\n")
            + TEXT("model_options = [{'id': 'model-a', 'label': 'Model A', 'provider': {'name': 'NVIDIA'}, 'contextLength': 128000}, {'optionId': 'model-b', 'name': 'Model B', 'vendor': 'Modal', 'maxInputTokens': 64000}, {'modelId': 'openai/gpt-5.5', 'name': 'openai/gpt-5.5'}]\n")
            + TEXT("thinking_options = [{'value': 'low', 'name': 'Low'}, {'value': 'medium', 'name': 'Medium'}, {'value': 'high', 'name': 'High'}]\n")
            + TEXT("agent_options = [{'value': 'build', 'name': 'Build'}, {'value': 'unreal-agent', 'name': 'Unreal Agent'}]\n")
            + TEXT("def send(obj): print(json.dumps(obj, separators=(',', ':')), flush=True)\n")
            + TEXT("def config_result(model=None, agent=None, thinking=None):\n")
            + TEXT("    global current_model, current_agent, current_thinking\n")
            + TEXT("    if model is not None: current_model = model\n")
            + TEXT("    if agent is not None: current_agent = agent\n")
            + TEXT("    if thinking is not None: current_thinking = thinking\n")
            + TEXT("    return {'configOptions': [{'configOptionId': 'preferred_model', 'category': 'current_model', 'optionValue': current_model, 'options': model_options}, {'id': 'effort', 'category': 'thought_level', 'currentValue': current_thinking, 'options': thinking_options}, {'id': 'mode', 'currentValue': current_agent, 'options': agent_options}]}\n")
            + TEXT("def validate_mcp_servers(params):\n")
            + TEXT("    servers = params.get('mcpServers', [])\n")
            + TEXT("    if not isinstance(servers, list) or len(servers) != 1: return 'expected one mcpServers entry'\n")
            + TEXT("    server = servers[0]\n")
            + TEXT("    if server.get('type') != 'http' or server.get('name') != 'unreal-engine' or server.get('url') != 'http://127.0.0.1:43123/mcp': return 'unexpected mcp server shape'\n")
            + TEXT("    if {'name': 'X-MCP-Capability-Token', 'value': 'fake-capability-token'} not in server.get('headers', []): return 'missing capability token header'\n")
            + TEXT("    return None\n")
            + TEXT("def prompt_text(msg): return ''.join([part.get('text', '') for part in msg.get('params', {}).get('prompt', []) if isinstance(part, dict)])\n")
            + TEXT("def request_permission(text):\n")
            + TEXT("    global permission_id\n")
            + TEXT("    permission_id += 1\n")
            + TEXT("    options = [] if text == 'no options path' else [{'optionId': 'once', 'kind': 'allow_once'}, {'optionId': 'always', 'kind': 'allow_always'}, {'optionId': 'reject', 'kind': 'reject_once'}]\n")
            + TEXT("    if text == 'mismatched always path': options = [{'optionId': 'always', 'kind': 'reject_once'}]\n")
            + TEXT("    send({'jsonrpc': '2.0', 'id': permission_id, 'method': 'session/request_permission', 'params': {'sessionId': session_id, 'toolCall': {'toolCallId': 'fake-tool', 'status': 'pending', 'title': 'fake permission', 'kind': 'execute', 'rawInput': {'prompt': text}}, 'options': options}})\n")
            + TEXT("for line in sys.stdin:\n")
            + TEXT("    if not line.strip(): continue\n")
            + TEXT("    msg = json.loads(line); method = msg.get('method'); msg_id = msg.get('id')\n")
            + TEXT("    if method == 'initialize': send({'jsonrpc': '2.0', 'id': msg_id, 'result': {'protocolVersion': 1}})\n")
            + TEXT("    elif method == 'session/new':\n")
            + TEXT("        err = validate_mcp_servers(msg.get('params', {}))\n")
            + TEXT("        if err is not None: send({'jsonrpc': '2.0', 'id': msg_id, 'error': {'code': -32602, 'message': err}}); continue\n")
            + TEXT("        result = {'sessionId': session_id}; result.update(config_result()); send({'jsonrpc': '2.0', 'id': msg_id, 'result': result})\n")
            + TEXT("    elif method == 'session/set_config_option':\n")
            + TEXT("        params = msg.get('params', {}); config_id = params.get('configId', params.get('id', '')); value = params.get('value', '')\n")
            + TEXT("        result = config_result(agent=value) if config_id == 'mode' else config_result(thinking=value) if config_id == 'effort' else config_result(model=value)\n")
            + TEXT("        send({'jsonrpc': '2.0', 'id': msg_id, 'result': result})\n")
            + TEXT("    elif method == 'session/prompt':\n")
            + TEXT("        prompt_id = msg_id; text = prompt_text(msg)\n")
            + TEXT("        send({'jsonrpc': '2.0', 'method': 'session/update', 'params': {'sessionId': session_id, 'update': {'sessionUpdate': 'agent_message_chunk', 'content': {'type': 'text', 'text': 'fake response: ' + text}}}})\n")
            + TEXT("        send({'jsonrpc': '2.0', 'method': 'session/update', 'params': {'sessionId': session_id, 'update': {'sessionUpdate': 'agent_thought_chunk', 'content': {'type': 'text', 'text': 'thinking about ' + text}}}})\n")
            + TEXT("        send({'jsonrpc': '2.0', 'method': 'session/update', 'params': {'sessionId': session_id, 'update': {'sessionUpdate': 'usage_update', 'used': 32000, 'size': 64000}}})\n")
            + TEXT("        send({'jsonrpc': '2.0', 'method': 'session/update', 'params': {'sessionId': session_id, 'update': {'sessionUpdate': 'tool_call', 'toolCallId': 'read-a', 'title': 'read', 'kind': 'read', 'rawInput': {'filePath': '/Game/SourceA.cpp'}, 'locations': [{'path': '/Game/SourceA.cpp'}]}}})\n")
            + TEXT("        send({'jsonrpc': '2.0', 'method': 'session/update', 'params': {'sessionId': session_id, 'update': {'sessionUpdate': 'tool_call_update', 'toolCallId': 'read-a', 'title': 'read', 'status': 'completed'}}})\n")
            + TEXT("        request_permission(text)\n")
            + TEXT("        if text == 'error after permission path': send({'jsonrpc': '2.0', 'id': prompt_id, 'error': {'code': -32000, 'message': 'fake prompt error'}}); prompt_id = None\n")
            + TEXT("        if text == 'no options path': send({'jsonrpc': '2.0', 'id': prompt_id, 'result': {'stopReason': 'end_turn'}}); prompt_id = None\n")
            + TEXT("    elif method == 'session/cancel' and prompt_id is not None: send({'jsonrpc': '2.0', 'id': prompt_id, 'result': {'stopReason': 'cancelled'}}); prompt_id = None\n")
            + TEXT("    elif msg_id is not None and 'result' in msg:\n")
            + TEXT("        outcome = msg.get('result', {}).get('outcome', {})\n")
            + TEXT("        if outcome.get('outcome') == 'selected' and prompt_id is not None:\n")
            + TEXT("            send({'jsonrpc': '2.0', 'method': 'session/update', 'params': {'sessionId': session_id, 'update': {'sessionUpdate': 'agent_message_chunk', 'content': {'type': 'text', 'text': ' permission option ' + outcome.get('optionId', '')}}}})\n")
            + TEXT("            send({'jsonrpc': '2.0', 'id': prompt_id, 'result': {'stopReason': 'end_turn'}}); prompt_id = None\n");
    }
}

#endif
