// Removes Python bytecode caches from td/ before packing. The npm `files`
// allowlist force-includes the whole td/ directory, which bypasses .npmignore —
// so __pycache__/*.pyc generated by running the bridge locally would otherwise
// leak into the published tarball. Wired to the `prepack` lifecycle hook.
import { readdirSync, rmSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const tdDir = resolve(dirname(fileURLToPath(import.meta.url)), "..", "td");
let removed = 0;

function walk(dir) {
  let entries;
  try {
    entries = readdirSync(dir, { withFileTypes: true });
  } catch {
    return;
  }
  for (const entry of entries) {
    const full = join(dir, entry.name);
    if (entry.isDirectory()) {
      if (entry.name === "__pycache__") {
        rmSync(full, { recursive: true, force: true });
        removed += 1;
      } else {
        walk(full);
      }
    } else if (entry.name.endsWith(".pyc")) {
      rmSync(full, { force: true });
      removed += 1;
    }
  }
}

walk(tdDir);
process.stdout.write(
  `[clean-pycache] removed ${removed} bytecode cache entr${removed === 1 ? "y" : "ies"} from td/\n`,
);
