import { commonSchemas } from '../../catalog/tool-definition-utils.js';
import type { ToolDefinition } from '../shared/tool-definition.js';
import { MATERIAL_AUTHORING_ACTIONS, TEXTURE_ACTIONS } from '../shared/action-sets.js';

export const manageAssetToolDefinition: ToolDefinition = {
    name: 'manage_asset',
    category: 'core',
    description: 'Create/import/manage assets, material graphs, material instances, procedural textures, render targets, and dependency analysis.',
    inputSchema: {
      type: 'object',
      properties: {
        action: {
          type: 'string',
          enum: [
            'list', 'import', 'duplicate', 'duplicate_asset', 'rename', 'rename_asset', 'move', 'move_asset', 'delete', 'delete_asset', 'delete_assets', 'create_folder', 'search_assets',
            'get_dependencies', 'get_source_control_state', 'analyze_graph', 'get_asset_graph', 'create_thumbnail', 'set_tags', 'get_metadata', 'set_metadata', 'validate', 'fixup_redirectors', 'find_by_tag', 'generate_report',
            'create_render_target', 'generate_lods', 'add_material_parameter', 'list_instances', 'reset_instance_parameters', 'exists', 'get_material_stats',
            'nanite_rebuild_mesh', 'bulk_rename', 'bulk_delete', 'source_control_checkout', 'source_control_submit',
            ...MATERIAL_AUTHORING_ACTIONS, ...TEXTURE_ACTIONS],
          description: 'Action to perform'
        },
        assetPath: commonSchemas.assetPath,
        directory: commonSchemas.directoryPath,
        classNames: commonSchemas.arrayOfStrings,
        packagePaths: commonSchemas.arrayOfStrings,
        recursivePaths: commonSchemas.booleanProp,
        recursiveClasses: commonSchemas.booleanProp,
        limit: commonSchemas.numberProp,
        offset: commonSchemas.numberProp,
        sourcePath: commonSchemas.sourcePath,
        destinationPath: commonSchemas.destinationPath,
        assetPaths: commonSchemas.arrayOfStrings,
        lodCount: commonSchemas.numberProp,
        posX: commonSchemas.numberProp,
        posY: commonSchemas.numberProp,
        newName: commonSchemas.newName,
        overwrite: commonSchemas.overwrite,
        save: commonSchemas.save,
        fixupRedirectors: commonSchemas.booleanProp,
        directoryPath: commonSchemas.directoryPath,
        name: commonSchemas.name,
        path: commonSchemas.directoryPath,
        parentMaterial: commonSchemas.materialPath,
        width: commonSchemas.numberProp,
        height: commonSchemas.numberProp,
        depth: commonSchemas.numberProp,
        format: commonSchemas.stringProp,
        meshPath: commonSchemas.meshPath,
        tag: commonSchemas.tagName,
        metadata: commonSchemas.objectProp,
        nodeType: commonSchemas.stringProp,
        nodeId: commonSchemas.nodeId,
        sourceNodeId: commonSchemas.sourceNodeId,
        targetNodeId: commonSchemas.targetNodeId,
        inputName: commonSchemas.pinName,
        parameterName: commonSchemas.parameterName,
        value: commonSchemas.value,
        x: commonSchemas.numberProp,
        y: commonSchemas.numberProp,
        maxDepth: commonSchemas.numberProp,
        // Bulk operations (C++ TryGetStringField)
        prefix: commonSchemas.stringProp,
        suffix: commonSchemas.stringProp,
        searchText: commonSchemas.stringProp,
        replaceText: commonSchemas.stringProp,
        paths: commonSchemas.arrayOfStrings,
        // Source control (C++ TryGetStringField)
        description: commonSchemas.stringProp,
        checkoutFiles: commonSchemas.booleanProp,
        // Bulk delete
        showConfirmation: commonSchemas.booleanProp,
        // Material graph operations
        pinName: commonSchemas.pinName,
        materialPath: commonSchemas.materialPath,
        texturePath: commonSchemas.texturePath,
        coordinateIndex: commonSchemas.numberProp,
        parameterType: commonSchemas.stringProp,
        tags: commonSchemas.arrayOfStrings,
        // Handler aliases (alternative parameter names accepted by handler)
        folderPath: commonSchemas.directoryPath,
        type: commonSchemas.stringProp,
        defaultValue: commonSchemas.value,
        force: commonSchemas.booleanProp,
        recursive: commonSchemas.booleanProp,
        reportType: commonSchemas.stringProp,
        pattern: commonSchemas.stringProp,
        replacement: commonSchemas.stringProp,
        materialDomain: commonSchemas.stringProp,
        blendMode: commonSchemas.stringProp,
        shadingModel: commonSchemas.stringProp,
        domain: commonSchemas.stringProp,
        twoSided: commonSchemas.booleanProp,
        uTiling: commonSchemas.numberProp,
        vTiling: commonSchemas.numberProp,
        operation: commonSchemas.stringProp,
        constA: commonSchemas.numberProp,
        constB: commonSchemas.numberProp,
        code: commonSchemas.stringProp,
        outputType: commonSchemas.stringProp,
        inputs: commonSchemas.arrayOfObjects,
        additionalOutputs: commonSchemas.arrayOfObjects,
        group: commonSchemas.stringProp,
        sourcePin: commonSchemas.sourcePin,
        targetPin: commonSchemas.targetPin,
        direction: commonSchemas.stringProp,
        downstream: commonSchemas.booleanProp,
        startNodeId: commonSchemas.nodeId,
        endPin: commonSchemas.pinName,
        orphansOnly: commonSchemas.booleanProp,
        functionPath: commonSchemas.assetPath,
        inputType: commonSchemas.stringProp,
        instancePath: commonSchemas.assetPath,
        layerName: commonSchemas.stringProp,
        blendType: commonSchemas.stringProp,
        layers: commonSchemas.arrayOfObjects,
        nodeIds: commonSchemas.arrayOfStrings,
        sourceTexture: commonSchemas.texturePath,
        strength: commonSchemas.numberProp,
        scale: commonSchemas.numberProp,
        octaves: commonSchemas.numberProp,
        samples: commonSchemas.numberProp,
        newWidth: commonSchemas.numberProp,
        newHeight: commonSchemas.numberProp,
        filterMethod: commonSchemas.stringProp,
        inBlack: commonSchemas.numberProp,
        inWhite: commonSchemas.numberProp,
        gamma: commonSchemas.numberProp,
        curvePoints: commonSchemas.arrayOfObjects,
        amount: commonSchemas.numberProp,
        radius: commonSchemas.numberProp,
        channel: commonSchemas.stringProp,
        redTexture: commonSchemas.texturePath,
        greenTexture: commonSchemas.texturePath,
        blueTexture: commonSchemas.texturePath,
        baseTexture: commonSchemas.texturePath,
        blendTexture: commonSchemas.texturePath,
        opacity: commonSchemas.numberProp,
        compressionSettings: commonSchemas.stringProp,
        textureGroup: commonSchemas.stringProp,
        lodBias: commonSchemas.numberProp,
        virtualTextureStreaming: commonSchemas.booleanProp,
        neverStream: commonSchemas.booleanProp,
        streamingPriority: commonSchemas.numberProp,
        speed: commonSchemas.numberProp,
        speedX: commonSchemas.numberProp,
        speedY: commonSchemas.numberProp,
        levels: commonSchemas.numberProp
      },
      required: ['action']
    },
    outputSchema: {
      type: 'object',
      properties: {
        ...commonSchemas.outputBase,
        assets: commonSchemas.arrayOfObjects,
        paths: commonSchemas.arrayOfStrings,
        path: commonSchemas.stringProp,
        nodeId: commonSchemas.nodeId,
        details: commonSchemas.objectProp,
        totalCount: commonSchemas.numberProp,
        offset: commonSchemas.numberProp,
        limit: commonSchemas.numberProp
      }
    }
  };
